import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#ffd8e7',
        'surface-container': '#ffe0ec',
        'inverse-surface': '#220214',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#000000',
        'tertiary-dim': '#004aad',
        'tertiary-fixed-dim': '#77a1ff',
        'on-tertiary-fixed': '#00163d',
        'surface-variant': '#ffd0e3',
        'secondary-fixed': '#5cfd80',
        'on-tertiary-container': '#002d6f',
        'on-tertiary': '#f0f2ff',
        'on-tertiary-fixed-variant': '#003580',
        'on-error-container': '#570008',
        primary: '#b60051',
        'surface-container-low': '#ffecf2',
        'on-primary-fixed-variant': '#5e0027',
        'on-background': '#492136',
        'tertiary-fixed': '#8eafff',
        'primary-container': '#ff7198',
        'on-secondary': '#cfffce',
        'surface-tint': '#b60051',
        'inverse-on-surface': '#c58da6',
        'surface-container-highest': '#ffd0e3',
        'on-primary': '#ffeff0',
        'surface-dim': '#ffc4dd',
        'primary-fixed': '#ff7198',
        'on-secondary-fixed-variant': '#006827',
        'secondary-fixed-dim': '#4bee74',
        'surface-bright': '#fff4f6',
        'on-error': '#ffefee',
        'error-dim': '#9f0519',
        surface: '#fff4f6',
        'on-secondary-fixed': '#004819',
        background: '#fff4f6',
        'on-primary-container': '#4d001e',
        'inverse-primary': '#ff4c85',
        'on-secondary-container': '#005d22',
        'primary-fixed-dim': '#ff5389',
        'on-surface-variant': '#7c4d64',
        tertiary: '#0055c4',
        'primary-dim': '#a00047',
        error: '#b31b25',
        outline: '#9b687f',
        'secondary-dim': '#005d22',
        'secondary-container': '#5cfd80',
        secondary: '#006a28',
        'tertiary-container': '#8eafff',
        'on-surface': '#492136',
        'error-container': '#fb5151',
        'outline-variant': '#d69db6',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
export default config;
